grade:
  image: registry.gitlab.com/rust-hse-tasks/rust-hse
  script:
    - echo $CI_PROJECT_DIR
    - echo $CI_COMMIT_REF_NAME
    - cargo test --manifest-path "/opt/hse/rust-hse/problems/add/Cargo.toml"
  timeout: 3 minutes
