grade:
  image: cr.yandex/crpn2tbct0clis87o7vk/ci-image
  script:
    - rover test --path "/opt/workspace/rust-hse/problems/$CI_COMMIT_REF_NAME" --move-files "$CI_PROJECT_DIR" --report-to manytask
  timeout: 3 minutes
